theme: "hugo-PaperMod"
baseURL: http://mathiasweidinger.github.io/
languageCode: en-us
title: Mathias Weidinger

menu:
  main:
    - name: About
      url: /about
      weight: 1
    # - name: Snaps
    #   url: /light
    #   weight: 3
    - name: Projects
      url: /current project
      weight: 2
    - name: Research
      url: /research
      weight: 3
    - name: Teaching
      url: /teaching
      weight: 4
    - name: Posts
      url: /post
      weight: 5
    - name: Contact
      url: /contact
      weight: 6
    - name: Find
      url: /search
      weight: 7
      

params:
  ShowCodeCopyButtons: true
  ShowShareButtons: false
  ShowReadingTime: true
  ShowToc: true
  ShowBreadCrumbs: false
  ShowPostNavLinks: true
  
  # params:
  # homeInfoParams:
  #   Title: Welcome to my website!
  #   Content: Let's talk economics, the environment, and sustainable human development.
  #   imageUrl: "android-chrome-512x512.png" # optional
  #   imageTitle: "<favicon>" # optional
  #   imageWidth: 150 # custom size
  #   imageHeight: 150 # custom size
  # 
  # socialIcons: # optional
  #   - name: "github"
  #     url: "https://github.com/mathiasweidinger"
  #   - name: "linkedin"
  #     url: "https://www.linkedin.com/in/envirodevonomic/"
  #   # - name: "twitter"
  #   #   url: "https://twitter.com/envirodevonomic"
  #   - name: "email"
  #     url: "mailto:mathias.weidinger@gmail.com"
  #   - name: "rss"
  #     url: "index.xml"
  
  profileMode:
    enabled: true
    title: |
      Welcome to my digital garden.

    subtitle: |
      Now growing ideas on economics, the environment, and sustainable human development.

    imageUrl: "android-chrome-512x512.png" # optional
    imageTitle: "<favicon>" # optional
    imageWidth: 150 # custom size
    imageHeight: 150 # custom size


  socialIcons:
    - name: "github"
      url: "https://github.com/mathiasweidinger"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/envirodevonomic/"
    - name: "twitter"
      url: "https://twitter.com/envirodevonomic"
    - name: "email"
      url: "mailto:mathias.weidinger@gmail.com"
    - name: "rss"
      url: "index.xml"
      
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

markup:
  goldmark:
    renderer:
      unsafe: true
